// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/Student.proto

package com.hsfeng.netty.proto;

public interface StudentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.hsfeng.protobuf.StudentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 age = 1;</code>
   * @return The age.
   */
  int getAge();
}
