// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/Student.proto

package com.hsfeng.netty.proto;

public interface StudentResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.hsfeng.protobuf.StudentResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.hsfeng.protobuf.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<com.hsfeng.netty.proto.StudentResponse> 
      getStudentResponseList();
  /**
   * <code>repeated .com.hsfeng.protobuf.StudentResponse studentResponse = 1;</code>
   */
  com.hsfeng.netty.proto.StudentResponse getStudentResponse(int index);
  /**
   * <code>repeated .com.hsfeng.protobuf.StudentResponse studentResponse = 1;</code>
   */
  int getStudentResponseCount();
  /**
   * <code>repeated .com.hsfeng.protobuf.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<? extends com.hsfeng.netty.proto.StudentResponseOrBuilder> 
      getStudentResponseOrBuilderList();
  /**
   * <code>repeated .com.hsfeng.protobuf.StudentResponse studentResponse = 1;</code>
   */
  com.hsfeng.netty.proto.StudentResponseOrBuilder getStudentResponseOrBuilder(
      int index);
}
